shrt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('url.urls')),
    path('admin/', admin.site.urls),
]

url/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from . import views
from . import api

app_name = 'url'

router = routers.DefaultRouter()
router.register(r'log', api.UrlLogViewSet)
router.register(r'url', api.UrlViewSet)


urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
    path('urls/', views.ListView.as_view(), name='urls'),
    re_path(r'^(?P<short>[A-Za-z0-9]{4})$', views.redirect_short, name='redirect'),
    re_path(r'^info/(?P<slug>[A-Za-z0-9]{4})$', views.DetailView.as_view(), name='info'),
]

url/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

from .lib import generator

class Url(models.Model):
    short = models.CharField(max_length=4, unique=True, null=False, blank=False, default=generator.random_string)
    url = models.URLField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True, null=False, blank=False)
    last_visited = models.DateTimeField(auto_now=True, null=False, blank=False)
    times_visited = models.BigIntegerField(default=0, blank=False)
    public = models.BooleanField(default=True, null=False, blank=False)

    def __str__(self):
        return f'{self.short} - {self.url}'
    

class UrlForm(ModelForm):
    class Meta:
        model = Url
        fields = ['url', 'public']
        widgets = {
            'url': forms.TextInput(attrs={'placeholder': 'URL'}),
        }


class UrlLog(models.Model):
    url = models.ForeignKey(Url, on_delete=models.CASCADE, null=False, blank=False)
    time = models.DateTimeField(auto_now_add=True, null=False, blank=False)
    source = models.GenericIPAddressField(null=False, blank=False)
    country_code = models.CharField(max_length=2, null=True)

    def __str__(self):
        return f'{self.url.short} - {self.source} ({self.country_code}): {self.time}'

url/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from geoip import geolite2
#from django.contrib.gis.geoip2 import GeoIP2

from .models import Url, UrlForm, UrlLog


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):
    if request.method == 'POST':
        form =  UrlForm(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect(reverse('url:info', args=(instance.short,)))
    else:
        form = UrlForm()
    return render(request, 'url/index.html', {'form': form})


def redirect_short(request, short):
    url = get_object_or_404(Url, short=short)
    url.times_visited += 1
    url.save()
    ip = get_client_ip(request)
    location = geolite2.lookup(ip)
    l = UrlLog(url=url, source=ip)
    if location:
        l.country_code = location.country
    l.save()
    return redirect(url.url)


class DetailView(generic.DetailView):
    model = Url
    slug_field = 'short'

class ListView(generic.ListView):
    model = Url
    paginate_by = 10
    ordering = ['-times_visited', '-created']
    queryset = Url.objects.filter(public=1)

url/templates/url/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>{{ title }}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="URL shortener">
        <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/navbar.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/icons.css" %}">
        <script src="{% static "js/base.js" %}"></script>
        {% block includes %}
        {% endblock includes %}
    </head>
    <body>
        <div class="container">
            <a href="https://github.com/tuggan/shrt" class="github-corner" aria-label="View source on GitHub">
                <svg id="github-corner-svg" width="80" height="80" viewBox="0 0 250 250" aria-hidden="true">
                    <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
                    <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
                    <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path>
                </svg>
            </a>


            <div class="header" id="header">shrt.nu</div>


            <div class="navbar">
                <a href="{% url 'url:index' %}" class="home {% if request.resolver_match.url_name == 'index' %}active{% endif %}"><span class="icon icon-home margin-right"></span>Home</a>
                <a href="{% url 'url:urls' %}" class="urls {% if request.resolver_match.url_name == 'urls' %}active{% endif %}"><span class="icon icon-database margin-right"></span>Urls</a>
                <a href="#" class="right register {% if request.resolver_match.url_name == 'register' %}active{% endif %}"><span class="icon icon-user-plus margin-right"></span>Register (WIP)</a>
                <a href="#" class="right login {% if request.resolver_match.url_name == 'login' %}active{% endif %}"><span class="icon icon-user margin-right"></span>Login (WIP)</a>
            </div>


    
            <div id="content">
                {% block content %}
                {% endblock %}
            </div> <!-- content -->
            <footer>
                <a href="http://shrt.nu">shrt.nu</a> <span id="copyright" class="nobreak">© <a href="mailto:dennisvesterlund@gmail.com">Dennis Vesterlund</span></a>
            </footer>
        </div> <!-- container -->
    </body>
</html>

url/templates/url/index.html
{% extends 'url/base.html' %}
{% load static %}
{% block includes %}
<link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
{% endblock includes %}

{% block content %}
    {% if form.url.errors %}
        <ol>
            {% for error in form.url.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
    {% endif %}

    <form action="{% url 'url:index' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="centered_input">
            <div class="form_wrapper{% if form.url.errors %} warn{% endif %}">{{ form.url }}</div><div class="button_wrapper"><input type="submit" value="Submit"></div>
            <label class="public_button" >Public
                {{ form.public }}
                <span class="checkmark"></span>
            </label>
        </div>
    </form>

{% endblock content %}

url/templates/url/short.html
{% extends 'url/base.html' %}
{% block content %}
    <h1>Short url here<h1>
    <a href="{% url 'url:redirect' short %}">{{ short }}</a>
{% endblock content %}

url/templates/url/url_detail.html
{% extends 'url/base.html' %}
{% load static %}
{% block includes %}
<script src="{% static "js/url_detail.js" %}"></script>
{% endblock includes %}
{% block content %}
    <table>
        <tr class="hidden">
            <td>ID:</td>
            <td id="url_id">{{ object.id }}</td>
        </tr>
        <tr>
            <td>Short URL:</td>
            <td><a href="{% url 'url:redirect' object.short %}">{{ object.short }}</a></td>
        </tr>
        <tr>
            <td>URL:</td>
            <td><a href="{{ object.url }}">{{ object.url }}</a></td>
        </tr>
        <tr>
            <td>Date added:</td>
            <td>{{ object.created }}</td>
        </tr>
        <tr>
            <td>Last visited:</td>
            <td>{{ object.last_visited }}</td>
        </tr>
        <tr>
            <td>Times visited:</td>
            <td>{{ object.times_visited }}</td>
        </tr>
        <tr>
            <td>Public:</td>
            <td>{{ object.public }}</td>
        </tr>
</table>
{% endblock content %}

url/templates/url/url_list.html
{% extends 'url/base.html' %}
{% block content %}
    <table>
        <thead>
            <tr>
                <td>Details</td>
                <td>Short URL</td>
                <td>URL</td>
                <td>Date added</td>
                <td>Last visited</td>
                <td>Times visited</td>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'url:info' object.short %}"><span class="icon icon-link-external"></span></a></td>
                    <td><a href="{% url 'url:redirect' object.short %}">{{ object.short }}</a></td>
                    <td><a href="{{ object.url }}">{{ object.url }}</a></td>
                    <td>{{ object.created }}</td>
                    <td>{{ object.last_visited }}</td>
                    <td>{{ object.times_visited }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}